### ISSUE TITLE
Hubitat nodes crashing Node-RED

### ISSUE THREAD

**Issue by bkdfkup** [fblackburn1/node-red-contrib-hubitat#74]
Hi!

I am hitting an issue with (some) node-red-contrib-hubitat nodes crashing node-RED, requiring a --safe restart and disabling flows until i can get it to stay working. The following error appears in an SSH terminal during the crash, grateful for any guidance to identify the culprit:

24 Nov 08:51:40 - [info] Started flows
24 Nov 08:51:40 - [red] Uncaught Exception:
24 Nov 08:51:40 - TypeError: Cannot read property 'attributes' of undefined
at HubitatDeviceNode._inputCallback (/home/bkdfkup/.node-red/node_modules/node-red-contrib-hubitat/nodes/device.js:171:56)
at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)
at HubitatDeviceNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
at HubitatDeviceNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
at HubitatDeviceNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)
at Immediate. (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:657:52)
at processImmediate (node:internal/timers:463:21)
at process.topLevelDomainCallback (node:domain:144:15)
at process.callbackTrampoline (node:internal/async_hooks:127:14)

**Comment by bkdfkup** [comment]
OK, i have narrowed it down to this only occurring if "Inject once after 0.1 seconds, then" is enabled in the inject node. If this is disabled, all works as expected, with the Hubitat node updating its values every 1 second. It seems odd that the initial injection is having an impact.

**Comment by fblackburn1** [comment]
Thank you, I can reproduce :+1:

Out of curiosity, what is the use case to use inject node without delay on device node?
If you don't wait a little bit, the cache will be not initialized and you will have not really useful information

**Comment by fblackburn1** [comment]
Fixed in 1.4.2 :smiley:

**Comment by bkdfkup** [comment]
Thanks very much!!! Will test tonight.
